# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1719ed8e0549f6aaf8e91ba41e3ea479"
name = "setting-app"
handle = "setting-app"
application_url = "https://case-conference-dynamic-though.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "store-test-165.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://case-conference-dynamic-though.trycloudflare.com/auth/callback",
  "https://case-conference-dynamic-though.trycloudflare.com/auth/shopify/callback",
  "https://case-conference-dynamic-though.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
